//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingApp.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrackingApp.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 創建報告.
        /// </summary>
        public static string ButtonCreateReport {
            get {
                return ResourceManager.GetString("ButtonCreateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登入.
        /// </summary>
        public static string ButtonLogin {
            get {
                return ResourceManager.GetString("ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        public static string ButtonUpdate {
            get {
                return ResourceManager.GetString("ButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增檢驗報表.
        /// </summary>
        public static string CheckReportCreate {
            get {
                return ResourceManager.GetString("CheckReportCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日期.
        /// </summary>
        public static string CheckReportDate {
            get {
                return ResourceManager.GetString("CheckReportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 司機名稱.
        /// </summary>
        public static string CheckReportDriver {
            get {
                return ResourceManager.GetString("CheckReportDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 供應商.
        /// </summary>
        public static string CheckReportSupplier {
            get {
                return ResourceManager.GetString("CheckReportSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檢查報告.
        /// </summary>
        public static string CheckReportTitle {
            get {
                return ResourceManager.GetString("CheckReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 貨車.
        /// </summary>
        public static string CheckReportTruckNo {
            get {
                return ResourceManager.GetString("CheckReportTruckNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  物資在庫.
        /// </summary>
        public static string InventoryLabel {
            get {
                return ResourceManager.GetString("InventoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 庫存數量.
        /// </summary>
        public static string InventoryQty {
            get {
                return ResourceManager.GetString("InventoryQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尺寸.
        /// </summary>
        public static string InventorySize {
            get {
                return ResourceManager.GetString("InventorySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 庫存清單.
        /// </summary>
        public static string InventoryTitle {
            get {
                return ResourceManager.GetString("InventoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBM.
        /// </summary>
        public static string InventoryVolumne {
            get {
                return ResourceManager.GetString("InventoryVolumne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 繁體.
        /// </summary>
        public static string LanguageChinese {
            get {
                return ResourceManager.GetString("LanguageChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 簡體.
        /// </summary>
        public static string LanguageChineseGB {
            get {
                return ResourceManager.GetString("LanguageChineseGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檢驗.
        /// </summary>
        public static string menuCheckReport {
            get {
                return ResourceManager.GetString("menuCheckReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首頁.
        /// </summary>
        public static string menuHome {
            get {
                return ResourceManager.GetString("menuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 庫存.
        /// </summary>
        public static string menuInventory {
            get {
                return ResourceManager.GetString("menuInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        public static string menuOperation {
            get {
                return ResourceManager.GetString("menuOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的.
        /// </summary>
        public static string menuUserInfo {
            get {
                return ResourceManager.GetString("menuUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此設定需要重新啟動.
        /// </summary>
        public static string messageChangeLanguage {
            get {
                return ResourceManager.GetString("messageChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查詢貨單.
        /// </summary>
        public static string OperationSearch {
            get {
                return ResourceManager.GetString("OperationSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入庫操作.
        /// </summary>
        public static string OperationStockIn {
            get {
                return ResourceManager.GetString("OperationStockIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出庫操作.
        /// </summary>
        public static string OperationStockOut {
            get {
                return ResourceManager.GetString("OperationStockOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 庫位轉移.
        /// </summary>
        public static string OperationTransfer {
            get {
                return ResourceManager.GetString("OperationTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請選擇你的操作.
        /// </summary>
        public static string OperationType {
            get {
                return ResourceManager.GetString("OperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查詢進出貨單.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  單未完成.
        /// </summary>
        public static string OrderLabel {
            get {
                return ResourceManager.GetString("OrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本更新.
        /// </summary>
        public static string SettingAppUpdate {
            get {
                return ResourceManager.GetString("SettingAppUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 語言.
        /// </summary>
        public static string SettingChangeLanguage {
            get {
                return ResourceManager.GetString("SettingChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出登錄.
        /// </summary>
        public static string SettingLogout {
            get {
                return ResourceManager.GetString("SettingLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料同步.
        /// </summary>
        public static string SettingSync {
            get {
                return ResourceManager.GetString("SettingSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户.
        /// </summary>
        public static string SettingUser {
            get {
                return ResourceManager.GetString("SettingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查詢進貨單.
        /// </summary>
        public static string StockInOrder {
            get {
                return ResourceManager.GetString("StockInOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  單未完成.
        /// </summary>
        public static string StockInOrderLabel {
            get {
                return ResourceManager.GetString("StockInOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查詢出貨單.
        /// </summary>
        public static string StockOutOrder {
            get {
                return ResourceManager.GetString("StockOutOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  單未完成.
        /// </summary>
        public static string StockOutOrderLabel {
            get {
                return ResourceManager.GetString("StockOutOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 員工編號.
        /// </summary>
        public static string UserAccount {
            get {
                return ResourceManager.GetString("UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 員工電子郵件.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 員工登錄.
        /// </summary>
        public static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密碼.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户資料.
        /// </summary>
        public static string UserTitle {
            get {
                return ResourceManager.GetString("UserTitle", resourceCulture);
            }
        }
    }
}
